In [1]:
import pandas as pd

df = pd.read_csv('../data/imdb_top_1000.csv')
df.head()

,rank,year,duration,age_limit,rating,numberof_ratings,Metascore,description,name
0,1,1994,2h 22m,15,9.3,(2.9M),82.0,"Over the course of several years, two convicts...",The Shawshank Redemption
1,2,1972,2h 55m,15,9.2,(2M),100.0,The aging patriarch of an organized crime dyna...,The Godfather
2,3,2008,2h 32m,12A,9.0,(2.9M),84.0,When the menace known as the Joker wreaks havo...,The Dark Knight
3,4,2003,3h 21m,12A,9.0,(2M),94.0,Gandalf and Aragorn lead the World of Men agai...,The Lord of the Rings: The Return of the King
4,5,1993,3h 15m,15,9.0,(1.5M),95.0,"In German-occupied Poland during World War II,...",Schindler's List

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rank              1000 non-null   int64
 1   year              1000 non-null   int64
 2   duration          1000 non-null   str
 3   age_limit         997 non-null    str
 4   rating            1000 non-null   float64
 5   numberof_ratings  1000 non-null   str
 6   Metascore         842 non-null    float64
 7   description       1000 non-null   str
 8   name              1000 non-null   str
dtypes: float64(2), int64(2), str(5)
memory usage: 70.4 KB

In [3]:
df.isnull().sum()

rank                  0
year                  0
duration              0
age_limit             3
rating                0
numberof_ratings      0
Metascore           158
description           0
name                  0
dtype: int64

In [4]:
df['duration'].head(10)
df['numberof_ratings'].head(10)

0    (2.9M)
1      (2M)
2    (2.9M)
3      (2M)
4    (1.5M)
5    (871K)
6    (1.4M)
7      (2M)
8    (2.2M)
9    (119K)
Name: numberof_ratings, dtype: str

In [5]:
def convert_votes(value):
    value = value.strip('()')
    if 'M' in value:
        return float(value.replace('M', ''))
    elif 'K' in value:
        return float(value.replace('K', ''))
    else:
        return float(value)
df['numberof_ratings'] = df['numberof_ratings'].apply(convert_votes)

In [10]:
df['numberof_ratings'].head(10)
df['numberof_ratings'].dtype

dtype('float64')

In [11]:
df['duration'].head(10)

0    2h 22m
1    2h 55m
2    2h 32m
3    3h 21m
4    3h 15m
5    1h 36m
6    3h 22m
7    2h 58m
8    2h 34m
9    2h 27m
Name: duration, dtype: str

In [12]:
def convert_duration(value):
    parts = value.split('h')
    hours = int(parts[0].strip())
    minutes = int(parts[1].replace('m', '').strip())
    return hours * 60 + minutes
df['duration'] = df['duration'].apply(convert_duration)

ValueError: invalid literal for int() with base 10: ''

In [13]:
df[~df['duration'].str.contains('m')]

,rank,year,duration,age_limit,rating,numberof_ratings,Metascore,description,name
92,93,2023,3h,15,8.3,755.0,90.0,The story of American scientist J. Robert Oppe...,Oppenheimer
98,99,2003,2h,18,8.3,640.0,78.0,After being kidnapped and imprisoned for fifte...,Oldboy
140,141,2013,3h,18,8.2,1.6,75.0,"Based on the true story of Jordan Belfort, fro...",The Wolf of Wall Street
211,212,2015,2h,15,8.1,1.1,90.0,"In a post-apocalyptic wasteland, a woman rebel...",Mad Max: Fury Road
230,231,1986,2h,15,8.1,442.0,92.0,"Chris Taylor, a neophyte recruit in Vietnam, f...",Platoon
247,248,1976,2h,PG,8.1,632.0,70.0,A small-time Philadelphia boxer gets a supreme...,Rocky
322,323,1986,2h,PG,8.1,28.0,NaN,A greedy landowner and his backward nephew con...,Jean de Florette
383,384,2008,2h,15,8.0,880.0,84.0,A teenager from the slums of Mumbai becomes a ...,Slumdog Millionaire
384,385,1989,2h,18,8.0,113.0,93.0,On the hottest day of the year on a street in ...,Do the Right Thing
421,422,1953,2h,PG,8.0,59.0,84.0,After two Americans are killed while escaping ...,Stalag 17
495,496,1993,3h,18,7.9,35.0,47.0,Based on the true life experiences of poet Jim...,"Blood In, Blood Out"
514,515,2000,2h,12,7.9,282.0,94.0,A young Chinese warrior steals a sword from a ...,"Crouching Tiger, Hidden Dragon"
542,543,2002,2h,12A,7.9,188.0,85.0,"A defense officer, Nameless, was summoned by t...",Hero
569,570,1980,3h,PG,7.9,38.0,84.0,A petty thief with an utter resemblance to a s...,Kagemusha
637,638,2010,2h,12A,7.8,763.0,95.0,As Harvard student Mark Zuckerberg creates the...,The Social Network
780,781,2013,3h,18,7.7,164.0,90.0,"Adèle's life is changed when she meets Emma, a...",Blue Is the Warmest Colour
796,797,1986,2h,18,7.7,217.0,75.0,The discovery of a severed human ear found in ...,Blue Velvet
823,824,2012,2h,15,7.7,641.0,86.0,Acting under the cover of a Hollywood producer...,Argo
860,861,2019,2h,15,7.7,152.0,82.0,A heavy metal drummer's life is turned upside ...,Sound of Metal
903,904,1966,2h,U,7.7,37.0,72.0,"The story of Sir Thomas More, who stood up to ...",A Man for All Seasons
904,905,2001,2h,18,7.7,96.0,59.0,"For two weeks, 20 male participants are hired ...",Das Experiment
935,936,2006,2h,15,7.7,37.0,78.0,A manager of an orphanage in India is sent to ...,After the Wedding
953,954,1992,2h,15,7.6,142.0,68.0,Two New Yorkers accused of murder in rural Ala...,My Cousin Vinny

In [14]:
def convert_duration(value):
    hours = 0
    minutes = 0
    if 'h' in value:
        parts = value.split('h')
        hours = int(parts[0].strip())
        remainder = parts[1].replace('m', '').strip()
        if remainder:  # only convert if not empty
            minutes = int(remainder)
    return hours * 60 + minutes

df['duration'] = df['duration'].apply(convert_duration)

In [15]:
df['duration'].head(10)
df['duration'].dtype

dtype('int64')

In [16]:
df['age_limit'].value_counts()

age_limit
15           289
PG           238
12A          138
18           108
U             78
X             50
12            28
A             26
AA            22
Not Rated      6
R              6
Approved       3
PG-13          2
TV-MA          1
16             1
Rejected       1
Name: count, dtype: int64

In [17]:
df['age_limit'] = df['age_limit'].fillna('Not Rated')

In [18]:
df['age_limit'].isnull().sum()

np.int64(0)

In [19]:
df['Metascore'] = df['Metascore'].fillna(df['Metascore'].median())

In [20]:
df['Metascore'].isnull().sum()

np.int64(0)